// eslint-disable-next-line check-file/filename-naming-convention
export interface Resources {
  common: {
    about: {
      our_story: "Our Story";
      launch_2015: "Launced in 2015, Exclusive is South Asia’s premier online shopping makterplace with an active presense in Bangladesh. Supported by wide range of tailored marketing, data and service solutions, Exclusive has 10,500 sallers and 300 brands and serves 3 millioons customers across the region.";
      "1_million_offers": "Exclusive has more than 1 Million products to offer, growing at a very fast. Exclusive offers a diverse assotment in categories ranging from consumer.";
      sallers_active: "Sallers active our site";
      monthly_profit: "Mopnthly Produduct Sale";
      customer_active: "Customer active in our site";
      annual_gross: "Anual gross sale in our site";
      founder: "Founder";
      chairman: "Chairman";
      managing_director: "Managing Director";
      product_designer: "Product Designer";
    };
    account: {
      welcome: "Welcome!";
      my_profile: "My Profile";
      address_book: "Address Book";
      my_payment_options: "My Payment Options";
      my_orders: "My Orders";
      my_returns: "My Returns";
      my_cancellations: "My Cancellations";
      my_wishlist: "My Wishlist";
      edit_ur_profile: "Edit Your Profile";
      first_name: "First Name";
      last_name: "Last Name";
      address: "Address";
      password_changes: "Password Changes";
      new_password: "New Password";
      confirm_new_password: "Confirm New Password";
      current_password: "Current Password";
      save_changes: "Save Changes";
      cancel: "Cancel";
      email_not_verified: "Email Not Verified";
      send_verification_email: "Send Verification Email";
    };
    auth: {
      create_an_account: "Create an account";
      enter_ur_details_below: "Enter your details below";
      name: "Name";
      email_or_phone_number: "Email or phone number";
      password: "Password";
      create_account: "Create account";
      sign_up_with_google: "Sign up with Google";
      already_have_account: "Already have an account?";
      login: "Login";
      login_in_to_exclusive: "Login in to Exclusive";
      forget_password: "Forget Password";
      sign_in_with_google: "Sign in with Google";
      login_successfully: "Login successfully";
      account_created_successfully: "Account created successfully";
    };
    cart: {
      return_to_shop: "Return to Shop";
      coupon_code: "Coupon Code";
      apply_coupon: "Apply Coupon";
      cart_total: "Cart Total";
      subtotal: "Subtotal";
      shipping: "Shipping";
      total: "Total";
      proceed_to_checkout: "Proceed to Checkout";
      no_item: "No items in your cart";
      product: "Product";
      price: "Price";
      quantity: "Quantity";
      billings_details: "Billing Details";
      bank: "Bank";
      cash_on_delivery: "Cash on Delivery";
      place_order: "Place Order";
      complete_payment: "Complete Payment";
      choose_ur_preferred_payment: "Choose your preferred payment method";
      pay_now: "Pay Now";
      standard_checkout: "Standard Checkout";
      express_checkout: "Express Checkout";
    };
    collection: {
      women_collections: "Women's Collections";
      women_description: "Featured woman collections that give you another vibe.";
      ps5_title: "PlayStation 5";
      ps5_description: "Black and White version of the PS5 coming out on sale.";
      speakers_title: "Speakers";
      speakers_description: "Amazon wireless speakers";
      perfume_title: "Perfume";
      perfume_description: "GUCCI INTENSE OUD EDP";
    };
    common: {
      "sale-off": "Summer Sale For All Swim Suits And Free Express Delivery - OFF 50%! hehehe";
      "shop-now": "ShopNow";
      shop_now: "Shop Now";
      language: "Language";
      days: "Days";
      hours: "Hours";
      minutes: "Minutes";
      seconds: "Seconds";
      "add-to-cart": "Add To Cart";
      view_all: "View All";
      view_all_products: "View All Products";
      out_of_stock: "Out Of Stock";
      in_stock: "In Stock";
      please_login: "Please Login";
      removed_from_wishlist: "Removed from wishlist";
      added_to_wishlist: "Added to wishlist";
      already_in_wishlist: "Already in wishlist";
      failed_to_toggle_wishlist: "Failed to toggle wishlist";
      added_to_cart: "Added to cart";
      failed_to_add_to_cart: "Failed to add to cart";
      variant_updated_in_wishlist: "Variant updated in wishlist";
      variant_already_in_wishlist: "Variant already in wishlist";
      failed_to_update_variant: "Failed to update variant";
      return_to_shop: "Return to shop";
      manage_my_account: "Manage My Account";
      my_order: "My Order";
      my_cancellation: "My Cancellation";
      my_reviews: "My Reviews";
      logout: "Logout";
      click_to_zoom: "Click to zoom";
      login: "Login";
      login_to_save_wishlist: "Login to save wishlist";
      please_login_to_add_to_cart: "Please login to add to cart";
      please_enter_coupon_code: "Please enter coupon code";
      coupon_applied_successfully: "Coupon applied successfully";
      logout_successfully: "Logout successfully";
      buy_now: "Buy Now";
    };
    contact: {
      call_to_us: "Call to Us";
      we_are_available: "We are available 24/7, 7 days a week.";
      phone: "Phone";
      write_to_us: "Write to Us";
      fill_out_the_form: "Fill out our form and we will contact you within 24 hours.";
      ur_name: "Your Name";
      ur_email: "Your Email";
      ur_phone: "Your Phone";
      ur_message: "Your Message";
      send_messages: "Send Messages";
    };
    details: {
      free_delivery: "Free delivery";
      enter_postcode: "Enter your postal code for Delivery Availability";
      return_delivery: "Return Delivery";
      free_30_days_return: "Free 30 Days Delivery Returns.";
      details: "Details";
    };
    footer: {
      exclusive: "Exclusive";
      subscribe: "Subscribe";
      get_10_off: "Get 10% off your first order";
      enter_email: "Enter your email";
      support: "Support";
      address_line_1: "III Bijoy sarani, Dhaka,";
      address_line_2: "DH 1515, Bangladesh.";
      email: "exclusive@gmail.com";
      phone: "+88015-88888-9999";
      account: "Account";
      my_account: "My Account";
      login_register: "Login / Register";
      cart: "Cart";
      wishlist: "Wishlist";
      shop: "Shop";
      quick_link: "Quick Link";
      privacy_policy: "Privacy Policy";
      terms_of_use: "Terms Of Use";
      faq: "FAQ";
      contact: "Contact";
      download_app: "Download App";
      save_3_with_app: "Save $3 with App New User Only";
      copyright: "Copyright Rimel 2022. All right reserved";
    };
    form: {
      first_name: "First Name";
      company_name: "Company Name";
      street_address: "Street Address";
      apartment: "Apartment, floor, etc. (optional)";
      city: "Town/City";
      phone_number: "Phone Number";
      email_address: "Email Address";
      save_this_information_for_next_time: "Save this information for next time";
    };
    header: {
      "sale-off": "Summer Sale For All Swim Suits And Free Express Delivery - OFF 50%!";
      home: "Home";
      contact: "Contact";
      about: "About";
      signup: "Sign Up";
      search: "What are you looking for?";
    };
    heading: {
      flash_sale: "Flash Sale";
      browse: "Browse by Category";
      best_sales: "Best Selling Products";
      explore: "Explore Our Products";
      arrivals: "New Arrival";
    };
    hero: {
      categories: "Categories";
      title: "Enhance Your Music Experience";
      buy_now: "Buy Now!";
    };
    payment: {
      payment_successful: "Payment Successful";
      thank_u: "Thank you for your purchase. Your order has been successfully created.";
      continue_shopping: "Continue Shopping";
    };
    section: {
      today: "Today's";
      categories: "Categories";
      this_month: "This months";
      our_products: "Our Products";
      featured: "Featured";
      just_for_you: "Just For You";
      related_products: "Related Products";
    };
    service: {
      free_delivery: "FREE AND FAST DELIVERY";
      delivery_description: "Free delivery for all orders over $140";
      customer_service: "24/7 CUSTOMER SERVICE";
      customer_description: "Friendly 24/7 customer support";
      money_back: "MONEY BACK GUARANTEE";
      money_description: "We return money within 30 days";
    };
    wishlist: {
      wishlist: "Wishlist";
      move_all_to_bag: "Move all to bag";
      no_item: "No items in your wishlist";
      see_all: "See All";
      wishlist_empty: "Your wishlist is empty";
    };
  };
}

export default Resources;
